### ISSUE TITLE
GUIから送信した画像がTUIで表示できない

### ISSUE THREAD

**Issue by hamuchan214** [solithv/simple_chat#4]
<img width="576" alt="スクリーンショット 2024-12-10 14 29 07" src="https://github.com/user-attachments/assets/df443fac-7865-4bc8-962f-0a8ac54c49a8">

**Comment by solithv** [comment]
fixed with commit https://github.com/solithv/simple_chat/commit/ccb580f364375a498d905fc18186dcca264dba28

**Comment by solithv** [comment]
fixed with commit https://github.com/solithv/simple_chat/commit/ccb580f364375a498d905fc18186dcca264dba28
